// import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
// import Link from "next/link";
import Image from "next/image";
import NavBar from "~/components/navbar";

// import { api } from "~/utils/api";
import { useSession } from "next-auth/react";
import { api } from "~/utils/api";
import { db } from "~/server/db";

export default function Home() {
  const { data: sessionData } = useSession();

  const current = sessionData?.user.id; // Replace with the actual user ID
  const get = api.user.getUser.useQuery({ userId: current ?? "" });

  const num = async () => {
    console.log(get.data.organization.orgName);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="block">
        <header className="flex flex-col">
          <NavBar />
          <button onClick={() => num()}>butn</button>
        </header>
      </main>
    </>
  );
}

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//       </p>

//       {sessionData ? (
//         <>
//           <div className="text-white">{sessionData.user.name}</div>
//           <div className="text-white">{sessionData.user.email}</div>

//           <Image
//             src={sessionData.user.image ?? ""}
//             width={30}
//             height={30}
//             alt="User Profile"
//           />
//           <button
//             className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//             onClick={() => void signOut()}
//           >
//             Logout
//           </button>
//         </>
//       ) : (
//         <>
//           <button
//             className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//             onClick={() => void signIn("google", {})}
//           >
//             Google
//           </button>
//           <button
//             className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//             onClick={() => void signIn("discord", {})}
//           >
//             Discord
//           </button>
//         </>
//       )}
//     </div>
//   );
// }
